services:
  app:
    image: node:20-alpine
    command: sh -c "yarn && yarn dev"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: car-dealer
    networks:
      - nodejs

  mysql:
    image: mysql:8.0
    volumes:
      - car-dealer-mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: car-dealer
    networks:
      - nodejs

volumes:
  car-dealer-mysql-data:

networks:
  nodejs:
