services:
  app:
    build: .
    command: yarn dev
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: car-dealer
      MYSQL_USER: car-dealer
      MYSQL_PASSWORD: car-dealer@2024
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - car-dealer-mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: car-dealer
      MYSQL_USER: car-dealer
      MYSQL_PASSWORD: car-dealer@2024
volumes:
  car-dealer-mysql-data:
