services:
  app:
    build: .
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: dealer
      MYSQL_PASSWORD: 25091994
      MYSQL_DB: car-dealer
  mysql:
    image: mysql:8.0
    volumes:
      - car-dealer-mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 25091994
      MYSQL_DATABASE: car-dealer
      MYSQL_USER: dealer
      MYSQL_PASSWORD: 25091994
volumes:
  car-dealer-mysql-data:
